recipes:
    global:
        - applications::git
        - applications::wget
        - applications::pv
        - applications::htop
        - applications::ssh_config
    mac_os_x:
        - applications::espresso
        - applications::sequelpro
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::enable_safari_debug_menu
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
